server:
  servlet:
    context-path : /api/v1
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true


  datasource:
    url: "jdbc:mysql://localhost:3306/users_db"
    username: root
    password: chisom123
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


secret: Hexdert687sdfghujikol;0w

logging:
  level:
    org.springframework.web: DEBUG
